.TH TIMEZONES Command Line Tool 

.SH NAME
       timezones - A custom command for displaying time zones. Also available with visual mode.

.SH SYNOPSIS
       timezones [OPTIONS], timezones -vi

.SH DESCRIPTION
       The timezones command prints time date and timezones based on cities timzones. also available with visual mode which displays live time.


.SH OPTIONS
-in   Show India time (Asia/Kolkata)
-uk   Show UK time (Europe/London)
-hk   Show Hong Kong time
-d    Show Dubai time
-jp   Show Japan time
-mel  Show Melbourne time
.SH AUTHOR
       Written by Mohammed Shoaib.

.SH SEE ALSO
      date, timedatectl
