.TH TIMEZONES Command Line Tool 

.SH NAME
       timezones - A custom command for displaying time zones. Also available with visual mode.

.SH SYNOPSIS
       timezones [OPTIONS]

.SH DESCRIPTION
       The timezones command prints time date and timezones based on cities timzones. also available with visual mode which displays live time.

.SH OPTIONS

.SH -vi
.R open in visual mode
.SH -in
.R Show India time (Asia/Kolkata)
.SH -uk
.R  Show UK time (Europe/London)
.SH -hk
.R  Show Hong Kong time
.SH -d
.R    Show Dubai time
.SH -jp
.R   Show Japan time
.SH -mel
.R  Show Melbourne time
.SH AUTHOR
       Written by Mohammed Shoaib.

.SH SEE ALSO
      date, timedatectl
